// generated by documents/gen.lua — the shared sidebar + search boxvar NAV_PAGES = [
    { u: "index.html", t: "Overview" },
    { u: "quickstart.html", t: "Quick start" },
    { u: "concepts.html", t: "Concepts" },
    { u: "widgets.html", t: "Widgets" },
    { u: "theme.html", t: "Themes" },
    { u: "translate.html", t: "Translate" },
    { u: "edit.html", t: "Edit" },
    { u: "settings.html", t: "Settings" },
    { u: "layout.html", t: "Layout" },
    { u: "animation.html", t: "Animation" },
    { u: "render.html", t: "Rendering" },
    { u: "diagnostics.html", t: "Diagnostics" },
    { u: "faq.html", t: "FAQ" },
    { u: "migration.html", t: "Migration V3 → V4" }
];(function () {
    var here = location.pathname.split("/").pop() || "index.html";
    var html = '<h1>DXUI</h1><div class="sub">retained-mode UI for MTA:SA</div>'
        + '<input class="search" id="q" placeholder="search..." autocomplete="off">'
        + '<div class="hits" id="hits"></div>';
    for (var i = 0; i < NAV_PAGES.length; i++) {
        var p = NAV_PAGES[i];
        var on = p.u === here ? ' class="on"' : "";
        html += '<a href="' + p.u + '"' + on + ">" + p.t + "</a>";
    }
    document.getElementById("nav").innerHTML = html;
    var q = document.getElementById("q");
    var hits = document.getElementById("hits");
    q.addEventListener("input", function () {
        var v = q.value.toLowerCase();
        hits.innerHTML = "";
        if (v.length < 2 || typeof WIKI_INDEX === "undefined") return;
        var n = 0;
        for (var i = 0; i < WIKI_INDEX.length && n < 8; i++) {
            var e = WIKI_INDEX[i];
            if (e.t.toLowerCase().indexOf(v) >= 0 || e.x.toLowerCase().indexOf(v) >= 0) {
                hits.innerHTML += '<a href="' + e.u + '">' + e.t + "</a>";
                n++;
            }
        }
    });
})();
