--[[
    tests/loader.lua — DXUI V2

    Single manifest for loading all DXUI V2 modules in meta.xml order.
    Used by every test file instead of copy-pasting dofile lists.
]]

dofile("../client/utils/color.lua")
dofile("../client/core/node.lua")
dofile("../client/core/widget.lua")
dofile("../client/api/context.lua")
dofile("../client/api/ui.lua")
dofile("../client/layout/layout.lua")
dofile("../client/input/hit_test.lua")
dofile("../client/input/events.lua")
dofile("../client/input/dispatcher.lua")
dofile("../client/render/render_list.lua")
dofile("../client/render/renderer.lua")
dofile("../client/render/state.lua")
dofile("../client/render/effects.lua")
dofile("../client/render/backend_mta.lua")
dofile("../client/resources/manager.lua")
dofile("../client/style/theme.lua")
dofile("../client/text/text.lua")
dofile("../client/animation/easing.lua")
dofile("../client/animation/animation.lua")
dofile("../client/translation.lua")
dofile("../client/widgets/panel.lua")
dofile("../client/widgets/label.lua")
dofile("../client/widgets/image.lua")
dofile("../client/widgets/button.lua")
dofile("../client/widgets/toggle.lua")
dofile("../client/widgets/checkbox.lua")
dofile("../client/widgets/radiobutton.lua")
dofile("../client/widgets/slider.lua")
dofile("../client/widgets/progressbar.lua")
dofile("../client/widgets/edit.lua")
dofile("../client/widgets/scrollpanel.lua")
dofile("../client/widgets/gridlist.lua")
dofile("../client/widgets/tabpanel.lua")
dofile("../client/widgets/combobox.lua")
dofile("../client/widgets/popup.lua")
dofile("../client/widgets/contextmenu.lua")
dofile("../client/widgets/tooltip.lua")
dofile("../client/widgets/window.lua")
dofile("../client/widgets/memo.lua")
dofile("../client/widgets/menu.lua")
dofile("../client/widgets/selector.lua")
dofile("../client/widgets/switchbutton.lua")
dofile("../client/widgets/line.lua")
dofile("../client/widgets/layout.lua")
dofile("../client/widgets/scalepane.lua")
dofile("../client/widgets/builders.lua")

return DXUI
